services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromService:
          name: mysql-db
          type: pserv
          property: host
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: password
      - key: DB_NAME
        value: fish_info

  - type: pserv
    name: mysql-db
    plan: free
    env: docker
    dockerfilePath: ./mysql.Dockerfile
